### ISSUE TITLE
Artigos que estão sendo lidos pela comissão

### ISSUE THREAD

**Issue by gab0gomes** [Sysvale/careers#1]
Issue para que os membros da comissão informem qual artigo extra do material de apoio está sendo lido, conforme deliberado na [reunião do dia 29/10/2019.](https://github.com/Gabrielr2508/careers/wiki/Atas-de-Reuni%C3%A3o#29102019)

**Comment by gab0gomes** [comment]
Lerei o artigo do **Buffer**.

**Comment by RafaelGondi** [comment]
Lerei o artigo "Scaling UX: A 4-Step Framework for Design Leaders"

**Comment by karlosguimaraes** [comment]
Estou lendo o **fog creek compensation**

**Comment by gab0gomes** [comment]
As leituras foram debatidas, por isso fecharei a issue.
